package login;
//imprt com.connection.Record;


import login.erpRecord;
import login.Register_page;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mithun Kumar
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
   
   
   
   
    
    public login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLgForgetPass = new javax.swing.JLabel();
        lgbtn = new javax.swing.JButton();
        btnLgRegister = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();
        pfpassword = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 32, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 79, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 138, -1, -1));

        btnLgForgetPass.setBackground(new java.awt.Color(255, 255, 255));
        btnLgForgetPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLgForgetPass.setForeground(new java.awt.Color(0, 255, 255));
        btnLgForgetPass.setText("Forget Password ?");
        btnLgForgetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLgForgetPassMouseClicked(evt);
            }
        });
        jPanel1.add(btnLgForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 250, -1, -1));

        lgbtn.setBackground(new java.awt.Color(0, 204, 204));
        lgbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lgbtn.setText("Login");
        lgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgbtnActionPerformed(evt);
            }
        });
        jPanel1.add(lgbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 206, 217, -1));

        btnLgRegister.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLgRegister.setForeground(new java.awt.Color(0, 255, 255));
        btnLgRegister.setText("Register Now !");
        btnLgRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLgRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(btnLgRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 247, -1, 20));
        jPanel1.add(tfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 105, 217, 27));

        pfpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(pfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 162, 217, 26));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 32, 10, 222));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mithun Kumar\\Downloads\\erpppp-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 22, 169, 137));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 610, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mithun Kumar\\Desktop\\Acharya-Institute-of-Technology.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        setSize(new java.awt.Dimension(895, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgbtnActionPerformed
 //Login
 
           // LOGINBOTTOM:
        String uname = tfuser.getText();
        String pass = pfpassword.getText();
        int rg_id = erpRecord.loginCheck(uname, pass);
        if(rg_id !=0)
        {
            JOptionPane.showMessageDialog(null, "Login successfully !");
           new  HomePage().setVisible(true);
           dispose();
//            Home_page pd = new Home_page();
//            pd.setVisible(true);
//            pd.pack();
//        pd.setLocationRelativeTo(null);
//        pd.setDefaultCloseOperation(login_page.EXIT_ON_CLOSE);
//        this.dispose();
        }
        if(rg_id==0)
        {
            JOptionPane.showMessageDialog(this, "Invalid Username or password");
        }
        
       tfuser.setText("");
        pfpassword.setText("");                       
        
    }//GEN-LAST:event_lgbtnActionPerformed

    private void pfpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfpasswordActionPerformed

    private void btnLgRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLgRegisterMouseClicked

        // TODO add your handling code here:
        Register_page rg = new Register_page();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(login_page.EXIT_ON_CLOSE);
        this.dispose();
       
       
    }//GEN-LAST:event_btnLgRegisterMouseClicked

    private void btnLgForgetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLgForgetPassMouseClicked
        // TODO add your handling code here:
        
        Forget_page rg = new  Forget_page();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(login_page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnLgForgetPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLgForgetPass;
    private javax.swing.JLabel btnLgRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lgbtn;
    private javax.swing.JTextField pfpassword;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
}
